name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # LATEST STABLE
    - uses: dtolnay/rust-toolchain@stable
    - name: build stable
      run: cargo +stable build --verbose
    - name: test stable
      run: cargo +stable test --verbose
    - name: test stable --release
      run: cargo +stable test --release --verbose
    # MSRV
    - uses: dtolnay/rust-toolchain@1.65.0
    - name: build MSRV
      run: cargo +1.65.0 build --verbose
    - name: test MSRV
      run: cargo +1.65.0 test --verbose
    - name: test MSRV --release
      run: cargo +1.65.0 test --release --verbose
